### PR TITLE
`time.clock` Deprecation Fixed

### LINKED ISSUE #149: Test fail with Python 3.8
https://github.com/enthought/scimath/blob/main/scimath/interpolate/tests/test_basic.py tests fail on Python 3.8. The issue is that the tests use `time.clock` which is not available in Python 3.8.

### PR DESCRIPTION
**Pull request by lnxpy**
- `time.clock()` method deprecation fixed with `time.process_time()`.
- `setUp()` method created.

Fixes #149.

### CODE REVIEW

**Comment by mdickinson** [comment]
Closing and re-opening to try to trigger GitHub Actions workflows

**Comment by mdickinson** [comment]
Thank you for the PR! There are a bunch of other mentions of `time.clock` in the `interpolate.py` file (in the main script). Would it be worth changing those as well in this PR?

**Comment by mdickinson** [comment]
Actually, I suspect that we should actually use `time.perf_counter` here rather than `time.process_time`: it looks as though the goal is timing of simple snippets.

**Comment by lnxpy** [comment]
Since, `time.time()` is deprecated, two proper alternatives would be `perf_counter` and `time_process`. `perf_counter` will measure the CPU time of a process. In the other hand, `time_process()` measures the sum of user time and CPU time of a process. I can fix them.

**Comment by lnxpy** [comment]
> Closing and re-opening to try to trigger GitHub Actions workflows

Worth mentioning the `pull_requests` event in the testing workflow?

**Comment by mdickinson** [comment]
> Worth mentioning the `pull_requests` event in the testing workflow?

It's already there. The issue was that the workflow was _also_ running on a cron job, and GitHub disables cron job-based workflows after some number of days of inactivity. So I had to re-enable the existing workflows.

**Comment by lnxpy** [comment]
> > Worth mentioning the `pull_requests` event in the testing workflow?
> 
> It's [already there](https://github.com/enthought/scimath/blob/a8780f8bdac319ed32de26d725d92f22eb45c580/.github/workflows/test-with-edm.yml#L6). The issue was that the workflow was _also_ running on a cron job, and GitHub disables cron job-based workflows after some number of days of inactivity. So I had to re-enable the existing workflows.

So then that would be cool if you set the events to `push` and `pull_request` in my opinion.

**Comment by mdickinson** [comment]
> So then that would be cool if you set the events to `push` and `pull_request` in my opinion.

Yes, that might make sense for some projects, but probably not this one. We don't do that in general across the Enthought Tool Suite because we often have work-in-progress branches that we're committing to, and we don't want each commit to trigger a workflow run. We only want commits to open PRs to trigger a workflow run.

**Review by mdickinson — COMMENTED** [review]
Code changes LGTM. I need to do manual testing of the `interpolate.py` main logic.

**Comment by lnxpy** [comment]
> > So then that would be cool if you set the events to `push` and `pull_request` in my opinion.
> 
> Yes, that might make sense for some projects, but probably not this one. We don't do that in general across the Enthought Tool Suite because we often have work-in-progress branches that we're committing to, and we don't want each commit to trigger a workflow run. We only want commits to open PRs to trigger a workflow run.

Didn't know that. Thanks for mentioning by the way. Good to know.

**Comment by lnxpy** [comment]
@mdickinson You're welcome. I have some questions. May I mail you in private?

**Comment by mdickinson** [comment]
> May I mail you in private?

Sure, go ahead. I'm working right now, though, so it may be a while before I'm able to respond.

**Pull request merged**
