### PR TITLE
Add a pyproject.toml file declaring NumPy as a build dependency.

### LINKED ISSUE #76: Declare build dependencies in pyproject.toml
scimath requires `numpy` in order to build, which means that a plain `pip install scimath` in an otherwise bare environment (+ pip, setuptools) will fail with something like this:
```
(scimath)bash-3.2$ pip install scimath
Collecting scimath
  Downloading https://files.pythonhosted.org/packages/fc/cf/cae77166021b4624a503656e0ba0423fc948c6615c997ec931b2c2e951e2/scimath-4.2.0.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 5.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/07/jbbjv8b53bs5y9xyjdyn1zgw0000gn/T/pip-install-h1q74gmd/scimath/setup.py", line 8, in <module>
        import numpy.distutils.core
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/07/jbbjv8b53bs5y9xyjdyn1zgw0000gn/T/pip-install-h1q74gmd/scimath/

```

Modern `pip` allows for a `pyproject.toml` file to specify build dependencies. See https://github.com/enthought/ibm2ieee/blob/master/pyproject.toml for an example. Assuming that the NumPy build dependency is needed here, we could add a `pyproject.toml` file here.

### PR DESCRIPTION
**Pull request by mdickinson**
This PR adds a minimal `pyproject.toml` file to declare NumPy as a build dependency. Without this, a `pip install scimath` in an environment that doesn't have NumPy installed will fail.

See [PEP 518](https://www.python.org/dev/peps/pep-0518/) for more information on use of `pyproject.toml`.

This fixes #76.

### CODE REVIEW

**Comment by mdickinson** [comment]
This won't work as it stands: the `pyproject.toml` file needs to be included in the source distribution. We don't currently have a MANIFEST.in on this project.

**Comment by mdickinson** [comment]
Closing for now.

**Comment by mdickinson** [comment]
> This won't work as it stands: the `pyproject.toml` file needs to be included in the source distribution. We don't currently have a MANIFEST.in on this project.

@rahulporuri added the manifest template in #82. I've updated it to include `pyproject.toml`.

This is ready for review (though we won't really find out whether it's working until we push another release to PyPI).

**Comment by rahulporuri** [comment]
> This is ready for review (though we won't really find out whether it's working until we push another release to PyPI).

Should we do an alpha release or a dev release and upload eggs to PyPI? I don't know how PyPI supports such releases.

**Comment by mdickinson** [comment]
> Should we do an alpha release or a dev release and upload eggs to PyPI? I don't know how PyPI supports such releases.

Yes, could do, but I wouldn't bother with an alpha or dev release: just bump the last part of the version triple and call it a (full) bugfix release.

**Comment by rahulporuri** [comment]
> Yes, could do, but I wouldn't bother with an alpha or dev release: just bump the last part of the version triple and call it a (full) bugfix release.

Alright then. Go ahead and merge this PR and we can work on the bugfix release.

**Pull request merged**
