### PR TITLE
Bump version number to 4.1.3dev

### PR DESCRIPTION
**Pull request by jonathanrocher**
... since 4.1.2 was already released.

@timdiller Please take a look.

### CODE REVIEW

**Comment by mdickinson** [comment]
Should we be using PEP 440-compatible version numbers?  E.g., `4.1.3.dev0`?

**Comment by jonathanrocher** [comment]
Good point @mdickinson .  Hatcher requested the same (though mentionned PEP386).

**Comment by mdickinson** [comment]
Yes, I think PEP 386 is what we're using in practice.

**Comment by jonathanrocher** [comment]
@timdiller @mdickinson OK to merge?

**Comment by timdiller** [comment]
LGTM

**Pull request merged**
