### PR TITLE
Add manifest file

### LINKED ISSUE #79: Include LICENSE and related files in source distribution.
We don't currently have a MANIFEST.in file, so some of the files that should be present in the source distribution aren't there.

### PR DESCRIPTION
**Pull request by rahulporuri**
This PR adds a basic manifest file. Fixes #79 . Facilitates #78 .

### CODE REVIEW

**Comment by mdickinson** [comment]
Closing and re-opening to trigger Appveyor build

**Comment by rahulporuri** [comment]
@mdickinson do you have time to review this PR?

**Comment by mdickinson** [comment]
Looking.

**Comment by mdickinson** [comment]
Here's the diff of the sdist with the source tree. Everything looks fine except the `scimath/scimath/physical_quantities/tests` part; looks like maybe we're missing an `__init__.py`?

```
mirzakhani:ETS mdickinson$ diff -qtr scimath ~/Desktop/scimath-4.3.0.dev341 | sort
Only in /Users/mdickinson/Desktop/scimath-4.3.0.dev341/scimath: _version.py
Only in /Users/mdickinson/Desktop/scimath-4.3.0.dev341: PKG-INFO
Only in /Users/mdickinson/Desktop/scimath-4.3.0.dev341: scimath.egg-info
Only in /Users/mdickinson/Desktop/scimath-4.3.0.dev341: setup.cfg
Only in scimath/scimath/physical_quantities: tests
Only in scimath: .coveragerc
Only in scimath: .git
Only in scimath: .gitignore
Only in scimath: .travis.yml
Only in scimath: TODO.txt
Only in scimath: appveyor.yml
Only in scimath: ci-doc-requirements.txt
Only in scimath: ci-src-requirements.txt
Only in scimath: docs
Only in scimath: etstool.py
Only in scimath: install-edm-linux.sh
Only in scimath: install-edm-osx.sh
Only in scimath: install-edm-windows.cmd
```

**Comment by mdickinson** [comment]
Hmm. `scimath.interpolate.tests` doesn't have a package structure, either; I wonder why that's not being picked up in the diff.

**Pull request merged**
