### PR TITLE
Add Python 3.12 to test versions; drop Python 3.7

### PR DESCRIPTION
**Pull request by mdickinson**
This PR updates the Python test versions to include Python 3.12 and exclude Python 3.7 (which is now beyond end-of-life).

### CODE REVIEW

**Review by corranwebster — APPROVED** [review]
Looks good.

Do we want to add `python_requires` to the setup.py as well?

**Comment by mdickinson** [comment]
> Do we want to add python_requires to the setup.py as well?

Yes, that would be good. Done in [b2fedab](https://github.com/enthought/scimath/pull/180/commits/b2fedab68d4c4316c3a31a656055229b136945bd)

**Comment by mdickinson** [comment]
Also applied some formatting fixes to `setup.py` in [9d562d1](https://github.com/enthought/scimath/pull/180/commits/9d562d17c3aff921b6f87ab50ca719abac23fa1b), since I was looking at a wall of red underlines for the `setup` call in VS Code.

**Comment by mdickinson** [comment]
Okay, this is messier than I was expecting. I'm going to revert back to the original commit and just merge that, then look at what it takes to remove Python 3.6 support properly.

**Pull request merged**
