### PR TITLE
Updates Changelog to accurate content of the release

### PR DESCRIPTION
**Pull request by stefanoborini**
Resynced the changelog to the actual PRs that went into this post 4.1.2

### CODE REVIEW

**Comment by jonathanrocher** [comment]
Hey @stefanoborini . I was going to take a look at this, but there are conflicts with master. Mind resolving so that we can get the release done?

**Comment by JCorson** [comment]
@jonathanrocher @stefanoborini  I hope y'all don't mind. I went ahead and fixed the conflict on this PR. Seemed like it was getting pushed back and a release would be nice for a few projects.

**Comment by jonathanrocher** [comment]
LGTM

**Comment by JCorson** [comment]
@stefanoborini Ready for merging?

**Pull request merged**
